language: python
python:
- '3.6'
- nightly
install: pip install -r requirements/dev.txt
script: python -m pytest --cov=app tests/
after_success:
- pip install coveralls
- coverage run --source=flask_oauthlib setup.py -q nosetests
- coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: AIuK4fU6oRgRc4Asb0SQuy7pviSdCEVhe4s8xun2iiK1x/XABeeDNT7+V/GyQngShdmEJ+NW+TR5QKpG7cuPxI2vYlbjM/dUK9S7vQYsHnT6jk4CtzftF75huZvD0PFbsFIpfDltvkMWn+IlD5ZRw5T9p1dMPjTwlNuC3XC019X/0FoD4TUORFuKBtVV/uhbqmPeggyHlIi74VXznhr0S7WhlztIM33O73NUh+I6KBntgEQfOKcE6a/TyH1GsnDWljoMutdGOc+/AWkPDmcudGYe0//7qIaGHcg7Hupuq7mKZibPNk07HLepVb2HGWHT5woVTWZ3MmmZNr8pMzlhawEe8WmFGr83Ow75qsj/INZk6blzmyBAUC9NbbhLk34BgVAoctbQWG34HDHZhdUO+5FKo6U6Yxw90bnNL2ksN1/A2Eelb9SoRXDpl3W5vU1wjB9Q4waVOHrMm+IdbxdZXJABvdvz+582RrtEnqd40If/DOm4vlnrfsgDe7hMN/0415C48fW2+yTrbfe3G+36XIhEpcaFBSPNqqHm7J/SXHn6ca6PGlcbzsZTZpvUbRrG+Y7VbS9F9BoefeE96gn/2VpdtitXiRdSzb4kXKh69jt51XYeSFc1tHW3siKyVyciNv8R3wCgPm0uPW5zT4fXb51g+jhdfRNbXWWSJU2x76s=
  app: ms-analytics-stage
