language: python
python:
- '3.6'
- nightly
install: pip install -r requirements/dev.txt
script: python -m pytest --cov=app tests/
after_success:
- pip install coveralls
- coverage run --source=flask_oauthlib setup.py -q nosetests
- coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: eZNiuizm/+mX87ytzrWk5RMLdVF7ytgC/Y4PnhnSfQEvREdTB3jW03Wrl/S5FfYD21AotMtlEe0F7lQk/oUpQWCTk3xz4DkE/jYhypaQLHQwskvGvlNWqPBexgBCZlknGuSAw/AKeP9DVJzQIB7Hv/tX/eGeXgU0l7TlFE5WSPkZ9fvxvbEVj/Rd32LKPrEtcmWOfQGjKuavxICLRiQ7zQCWrppV/yTivsVhBHIoUkFa01cdtbHOQo4sArPVfrCd5ParD4RDvzMGpckAnTV0jN3tOf0L3FyWVmVZlcGI62eQP43EYiOmxg2L4ndTP/Y5OiPHfDOqa19dS85R5b/iBQDjS2vBa3rGZEPzv87qNY/+9/3g6AUaOihRprCKVISP2JG5V9IZlDaq0GWEnLdhwaZvv6PzNmOq39fAH8Lde971+rVtmBRkY0wg88zQL+2aLPnXbXMeUBskZO1svlfd6d7D3dV+05mpPt2Z1Fm6xZLUpJZob0/Mf2EFf34RWueJI4Cg3yvpU9cbCuGKWl3l9Ya2PEWLkoeKFuuiXeCOfZvQbPgSBlhWx1bWIR2R/V9Uk3gnsi12mvTyHB+SGcO6zAH53V0Ez+VBFJDKlCDbnQKm6V+RbbvOtKuZTkL3H3X6cIzQJn6fxN/ybEpEp4KaAt1HzQ0JXdW2yiCxcoz1JSU=
  app: ms-analytics-stage
