language: python
python:
- '3.6'
- nightly
install: pip install -r requirements/dev.txt
script: python -m pytest --cov=app tests/
after_success:
- pip install coveralls
- coverage run --source=flask_oauthlib setup.py -q nosetests
- coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ciRfxSYVcQeC9l9T9bXelgP+owX95NYnqiQ5bRNCVgrfNzUAR2kWtujTY2pWb/hMoNvx8EAs3wMGNx9P/XGhEBdSsrwclIdpTr1/BxdtiorcJvhbVGK0u5WvOcCDLrbTJ7iXHmjlX7sphjBfbg/0lkDatbHqgOpZMAoz6J9IDuuYsPC+56l/Flrsy1wRcq2JgW/vMVwfoQZRECi4xEiGChJJlKadla45rEO2OMcWB2Qpwb8XgtWJykEa5P3AnQ0Ij7yvOPjGMfIuXYUF6zhDlDfEf8bUoCnVF2czxrFx7K3+Gyq+xeTcvZcRaWQg45E3deMVuoaINpyCyYg/3xDospi530kJIXv8MfoT0n8u8rOlRRy42YoFAwZd/8V9dY/sxAKfgm/gzTLSDVzZdacjO3Fl+tWu6/RgyFy0MW4VANBukJGvEPqwJ0oINMkOhki+fTl4yNZsX2rYcdSkII2CTup5/kEPWT5nDR3LohjnvwAj18jq3mfe8u+4CMWck+CsrmWxU/ww7Nuw05m6Dmz0mrTJgCYMFaxX+YIwZxssZhFuu3of8FJJ6NCDXo6Lyma/+sZUwp9IqNqyYJ1Ar16OtbyNExIMWAbBZaBl+t5DZEIC8eLyhJPmWfHXDG0wrKkmHFtFiB+1VviDv1bpAwiec2oqp8hemf9exHgPLkXZyDQ=
  app: ms-analytics-stage
